"""
Standalone comparison harness: build a FakeCosmoData backed directly by
sigma(M)/delta_col(z) tables dumped from the *actual* PCH08 reference FORTRAN
code (Parkinson's own split_PCH.F90/make_tree.F90/trees.F90, e.g. as found at
~/Codes/mctrees), so PCHMergerTree's Python machinery runs against exactly
the same P(k)/growth-factor numbers the FORTRAN used. This lets
full-population branch counts be compared directly against a FORTRAN run's
own per-checkpoint fragment counts (nhalolev(ilev) in make_tree.F90's own
output), with no camb/CosmoData/cosmology-mismatch confound. This is how the
sign error fixed in pch_trees.py's _branching_rate_terms/_build_forest_kernel
(2.0**(mu*gamma1) -> 2.0**(-mu*gamma1)) was found: internal self-consistency
checks (foraois.diagnostics.check_sampling_consistency) cannot catch a bug
shared between a rate formula and its own self-derived target, so an
external, independently-authored reference implementation was needed.

fortran_reference_data/{sigma_table.dat,deltac_table.dat} (checked into this
repo alongside this script) were generated by fortran_reference_data/
sigma_dump.F90, compiled and linked against the same cosmology/parameter
setup as Parkinson's trees.F90 (Millennium-like: Omega0=0.25, Lambda0=0.75,
h0=0.73, sigma8=0.9, BBKS transfer function, G0=0.57/gamma1=0.38/gamma2=-0.01,
eps1=eps2=0.1) -- see that file's own header. Regenerate them (with a
different cosmology, or after any change to the reference FORTRAN) by
compiling sigma_dump.F90 against the same object files as trees.exe (num_pars,
defined_types, kind_numbers, parameter_modules, memory_modules, tree_routines,
modified_merger_tree, deltcrit, memory, sigmacdm_spline, interp, locate,
hyperbolic, ran3, spline, indexxx, transfer_function, unresolved_mass,
parameters) and running the resulting executable from a directory containing
pk_Mill.dat and a Data/flat.data file (both part of the reference FORTRAN
codebase, not included here).
"""
import os
import sys

import numpy as np
from scipy.interpolate import interp1d

sys.path.insert(0, "scripts/paper_figs")

from foraois.pch_trees import PCHMergerTree

_DATA_DIR = os.path.join(os.path.dirname(os.path.abspath(__file__)), "fortran_reference_data")
SIGMA_TABLE = os.path.join(_DATA_DIR, "sigma_table.dat")
DELTAC_TABLE = os.path.join(_DATA_DIR, "deltac_table.dat")


class FakeCosmoData:
    """Minimal CosmoData stand-in backed by the FORTRAN's own tables."""

    def __init__(self):
        sig = np.loadtxt(SIGMA_TABLE, skiprows=1)
        self._logmass_raw = sig[:, 0]
        self._sigma_raw = sig[:, 1]
        # FORTRAN's dumped alpha = dlnsigma/dlnM (signed, negative, matching
        # cosmo_utils.CosmoData's raw self._dlogsigma_dlogmass convention).
        # PCHMergerTree/_branching_rate_terms expects dlogsigma_at_logmass
        # to return the *positive* |dlnsigma/dlnM|, matching
        # CosmoData._dlogsigma_interp being built from np.abs(...) --
        # negate here to match that convention exactly.
        self._alpha_raw = -sig[:, 2]

        dc = np.loadtxt(DELTAC_TABLE, skiprows=1)
        self._dc_z_grid = dc[:, 0]
        self._dc_dc_grid = dc[:, 2]

        _kw = dict(kind="linear", bounds_error=False, fill_value="extrapolate", assume_sorted=True)
        self._sigma_interp = interp1d(self._logmass_raw, self._sigma_raw, **_kw)
        self._dlogsigma_interp = interp1d(self._logmass_raw, self._alpha_raw, **_kw)

    def get_power_spectrum(self):
        return None

    def _prepare_sigma_grid(self, pk_data, logmass_min=None, logmass_max=None, dlogmass=None):
        self._logmass = self._logmass_raw
        self._sigma = self._sigma_raw
        self._dlogsigma_dlogmass = self._alpha_raw

    def sigma_at_logmass(self, logmass):
        return self._sigma_interp(logmass)

    def dlogsigma_at_logmass(self, logmass):
        return self._dlogsigma_interp(logmass)

    def delta_col_at_z(self, z):
        return np.interp(z, self._dc_z_grid, self._dc_dc_grid)

    def precompute_delta_col_table(self, z_max=15.0, nz=5000):
        if z_max > self._dc_z_grid[-1]:
            raise ValueError(f"FORTRAN deltac table only covers z<={self._dc_z_grid[-1]}, need z_max={z_max}")


def build_pch():
    cosmo = FakeCosmoData()
    pch = PCHMergerTree(cosmo, {})
    return pch


if __name__ == "__main__":
    pch = build_pch()
    # Sanity check: reproduce a couple of table points
    print("sigma(1e13) =", pch._sigma_at_mass(1e13), " (FORTRAN table logM=13 -> sigma=?)")
    print("delta_col(0.5) =", pch._delta_col_at_z(0.5))
    print("delta_col(5.0) =", pch._delta_col_at_z(5.0))
